//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contingencia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errores() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contingencia.Errores", typeof(Errores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en archivo de configuración..
        /// </summary>
        internal static string ArchivoConfiguracion {
            get {
                return ResourceManager.GetString("ArchivoConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, el archivo no existe..
        /// </summary>
        internal static string ArchivoNoExiste {
            get {
                return ResourceManager.GetString("ArchivoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo está vacío..
        /// </summary>
        internal static string ArchivoVacio {
            get {
                return ResourceManager.GetString("ArchivoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, la clave ya existe..
        /// </summary>
        internal static string ClaveExiste {
            get {
                return ResourceManager.GetString("ClaveExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, clave inválida..
        /// </summary>
        internal static string ClaveInvalida {
            get {
                return ResourceManager.GetString("ClaveInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se logró conectar a la Base de Datos..
        /// </summary>
        internal static string ConexionBase {
            get {
                return ResourceManager.GetString("ConexionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al consultar registros..
        /// </summary>
        internal static string ConsultarRegistro {
            get {
                return ResourceManager.GetString("ConsultarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al consultar variables de entorno..
        /// </summary>
        internal static string ConsultarVariablesEntorno {
            get {
                return ResourceManager.GetString("ConsultarVariablesEntorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error desconocido..
        /// </summary>
        internal static string Desconocido {
            get {
                return ResourceManager.GetString("Desconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Descripción Inválida..
        /// </summary>
        internal static string DescripcionInvalida {
            get {
                return ResourceManager.GetString("DescripcionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intentar eliminar registro..
        /// </summary>
        internal static string EliminarRegistro {
            get {
                return ResourceManager.GetString("EliminarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intentar insertar registro..
        /// </summary>
        internal static string InsertarRegistro {
            get {
                return ResourceManager.GetString("InsertarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation of PRIMARY KEY constraint.
        /// </summary>
        internal static string LlavePrimariaExiste {
            get {
                return ResourceManager.GetString("LlavePrimariaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El mensaje original es : .
        /// </summary>
        internal static string MensajeOriginal {
            get {
                return ResourceManager.GetString("MensajeOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intentar modificar el registro..
        /// </summary>
        internal static string ModificarRegistro {
            get {
                return ResourceManager.GetString("ModificarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros..
        /// </summary>
        internal static string NoRegistros {
            get {
                return ResourceManager.GetString("NoRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha seleccionado un registro válido..
        /// </summary>
        internal static string NoRegistroValido {
            get {
                return ResourceManager.GetString("NoRegistroValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la variable de entorno, verifique el archivo de configuración de la aplicación..
        /// </summary>
        internal static string NoVariableEntorno {
            get {
                return ResourceManager.GetString("NoVariableEntorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, el usuario no existe..
        /// </summary>
        internal static string UsuarioNoExiste {
            get {
                return ResourceManager.GetString("UsuarioNoExiste", resourceCulture);
            }
        }
    }
}
