//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contingencia {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Procedimientos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Procedimientos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contingencia.Procedimientos", typeof(Procedimientos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ActualizaDestinoZmaster.
        /// </summary>
        internal static string sp_ActualizaDestinoZmaster {
            get {
                return ResourceManager.GetString("sp_ActualizaDestinoZmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ActualizarFatomCodDestino.
        /// </summary>
        internal static string sp_ActualizarFatomCodDestino {
            get {
                return ResourceManager.GetString("sp_ActualizarFatomCodDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ActualizarFatomDestino.
        /// </summary>
        internal static string sp_ActualizarFatomDestino {
            get {
                return ResourceManager.GetString("sp_ActualizarFatomDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ActualizarFatomEntrega.
        /// </summary>
        internal static string sp_ActualizarFatomEntrega {
            get {
                return ResourceManager.GetString("sp_ActualizarFatomEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ActualizarFatomEstado.
        /// </summary>
        internal static string sp_ActualizarFatomEstado {
            get {
                return ResourceManager.GetString("sp_ActualizarFatomEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ActualizarFatomMateriales.
        /// </summary>
        internal static string sp_ActualizarFatomMateriales {
            get {
                return ResourceManager.GetString("sp_ActualizarFatomMateriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ActualizarFatomOrdenes.
        /// </summary>
        internal static string sp_ActualizarFatomOrdenes {
            get {
                return ResourceManager.GetString("sp_ActualizarFatomOrdenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ActualizarFatomOrdenesZPPG02.
        /// </summary>
        internal static string sp_ActualizarFatomOrdenesZPPG02 {
            get {
                return ResourceManager.GetString("sp_ActualizarFatomOrdenesZPPG02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ActualizarFatomOrdenVirtual.
        /// </summary>
        internal static string sp_ActualizarFatomOrdenVirtual {
            get {
                return ResourceManager.GetString("sp_ActualizarFatomOrdenVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ActualizarFatomPeso.
        /// </summary>
        internal static string sp_ActualizarFatomPeso {
            get {
                return ResourceManager.GetString("sp_ActualizarFatomPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ActualizarFatomProdVirt2.
        /// </summary>
        internal static string sp_ActualizarFatomProdVirt2 {
            get {
                return ResourceManager.GetString("sp_ActualizarFatomProdVirt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ActualizarPicking.
        /// </summary>
        internal static string sp_ActualizarPicking {
            get {
                return ResourceManager.GetString("sp_ActualizarPicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsCalidad.
        /// </summary>
        internal static string sp_ConsCalidad {
            get {
                return ResourceManager.GetString("sp_ConsCalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsCanalFin.
        /// </summary>
        internal static string sp_ConsCanalFin {
            get {
                return ResourceManager.GetString("sp_ConsCanalFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsCatAlmacenes.
        /// </summary>
        internal static string sp_ConsCatAlmacenes {
            get {
                return ResourceManager.GetString("sp_ConsCatAlmacenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsCatCalidad.
        /// </summary>
        internal static string sp_ConsCatCalidad {
            get {
                return ResourceManager.GetString("sp_ConsCatCalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsCatCentro.
        /// </summary>
        internal static string sp_ConsCatCentro {
            get {
                return ResourceManager.GetString("sp_ConsCatCentro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsCatDestino.
        /// </summary>
        internal static string sp_ConsCatDestino {
            get {
                return ResourceManager.GetString("sp_ConsCatDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsCatTipoAlmacen.
        /// </summary>
        internal static string sp_ConsCatTipoAlmacen {
            get {
                return ResourceManager.GetString("sp_ConsCatTipoAlmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsCatUbicaciones.
        /// </summary>
        internal static string sp_ConsCatUbicaciones {
            get {
                return ResourceManager.GetString("sp_ConsCatUbicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsCatZMaster.
        /// </summary>
        internal static string sp_ConsCatZMaster {
            get {
                return ResourceManager.GetString("sp_ConsCatZMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsClientes.
        /// </summary>
        internal static string sp_ConsClientes {
            get {
                return ResourceManager.GetString("sp_ConsClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsDetalle.
        /// </summary>
        internal static string sp_ConsDetalle {
            get {
                return ResourceManager.GetString("sp_ConsDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsEntorno.
        /// </summary>
        internal static string sp_ConsEntorno {
            get {
                return ResourceManager.GetString("sp_ConsEntorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsEntregas.
        /// </summary>
        internal static string sp_ConsEntregas {
            get {
                return ResourceManager.GetString("sp_ConsEntregas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsEstado.
        /// </summary>
        internal static string sp_ConsEstado {
            get {
                return ResourceManager.GetString("sp_ConsEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsFatom.
        /// </summary>
        internal static string sp_ConsFatom {
            get {
                return ResourceManager.GetString("sp_ConsFatom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsFolioFecha.
        /// </summary>
        internal static string sp_ConsFolioFecha {
            get {
                return ResourceManager.GetString("sp_ConsFolioFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsGrupoEmp.
        /// </summary>
        internal static string sp_ConsGrupoEmp {
            get {
                return ResourceManager.GetString("sp_ConsGrupoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsGrupoMat.
        /// </summary>
        internal static string sp_ConsGrupoMat {
            get {
                return ResourceManager.GetString("sp_ConsGrupoMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsInsFolioRegresaElRegistroInsertado.
        /// </summary>
        internal static string sp_ConsInsFolioRegresaElRegistroInsertado {
            get {
                return ResourceManager.GetString("sp_ConsInsFolioRegresaElRegistroInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsLIPS.
        /// </summary>
        internal static string sp_ConsLIPS {
            get {
                return ResourceManager.GetString("sp_ConsLIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsLote.
        /// </summary>
        internal static string sp_ConsLote {
            get {
                return ResourceManager.GetString("sp_ConsLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsMARA.
        /// </summary>
        internal static string sp_ConsMARA {
            get {
                return ResourceManager.GetString("sp_ConsMARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsMatnrFechaZMaster.
        /// </summary>
        internal static string sp_ConsMatnrFechaZMaster {
            get {
                return ResourceManager.GetString("sp_ConsMatnrFechaZMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsMatZMaster.
        /// </summary>
        internal static string sp_ConsMatZMaster {
            get {
                return ResourceManager.GetString("sp_ConsMatZMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsNumCajasTarima.
        /// </summary>
        internal static string sp_ConsNumCajasTarima {
            get {
                return ResourceManager.GetString("sp_ConsNumCajasTarima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsOPCS.
        /// </summary>
        internal static string sp_ConsOPCS {
            get {
                return ResourceManager.GetString("sp_ConsOPCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsOrdenProd.
        /// </summary>
        internal static string sp_ConsOrdenProd {
            get {
                return ResourceManager.GetString("sp_ConsOrdenProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsPLPO.
        /// </summary>
        internal static string sp_ConsPLPO {
            get {
                return ResourceManager.GetString("sp_ConsPLPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsRepoCanal.
        /// </summary>
        internal static string sp_ConsRepoCanal {
            get {
                return ResourceManager.GetString("sp_ConsRepoCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsRepoProducto.
        /// </summary>
        internal static string sp_ConsRepoProducto {
            get {
                return ResourceManager.GetString("sp_ConsRepoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsRepoRemision.
        /// </summary>
        internal static string sp_ConsRepoRemision {
            get {
                return ResourceManager.GetString("sp_ConsRepoRemision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsRepoRemisionCanal.
        /// </summary>
        internal static string sp_ConsRepoRemisionCanal {
            get {
                return ResourceManager.GetString("sp_ConsRepoRemisionCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsRepoResumen.
        /// </summary>
        internal static string sp_ConsRepoResumen {
            get {
                return ResourceManager.GetString("sp_ConsRepoResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsRepoResumenDetalle.
        /// </summary>
        internal static string sp_ConsRepoResumenDetalle {
            get {
                return ResourceManager.GetString("sp_ConsRepoResumenDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsRESB.
        /// </summary>
        internal static string sp_ConsRESB {
            get {
                return ResourceManager.GetString("sp_ConsRESB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsTablaTemporalZMaster.
        /// </summary>
        internal static string sp_ConsTablaTemporalZMaster {
            get {
                return ResourceManager.GetString("sp_ConsTablaTemporalZMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsTraspCalidad.
        /// </summary>
        internal static string sp_ConsTraspCalidad {
            get {
                return ResourceManager.GetString("sp_ConsTraspCalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsUsuarios.
        /// </summary>
        internal static string sp_ConsUsuarios {
            get {
                return ResourceManager.GetString("sp_ConsUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsZ_CAT.
        /// </summary>
        internal static string sp_ConsZ_CAT {
            get {
                return ResourceManager.GetString("sp_ConsZ_CAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsZ_CTC.
        /// </summary>
        internal static string sp_ConsZ_CTC {
            get {
                return ResourceManager.GetString("sp_ConsZ_CTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsZBASCULAS.
        /// </summary>
        internal static string sp_ConsZBASCULAS {
            get {
                return ResourceManager.GetString("sp_ConsZBASCULAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsZTPPLogs.
        /// </summary>
        internal static string sp_ConsZTPPLogs {
            get {
                return ResourceManager.GetString("sp_ConsZTPPLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsZTPPTrazabi.
        /// </summary>
        internal static string sp_ConsZTPPTrazabi {
            get {
                return ResourceManager.GetString("sp_ConsZTPPTrazabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ConsZTTPLogs.
        /// </summary>
        internal static string sp_ConsZTTPLogs {
            get {
                return ResourceManager.GetString("sp_ConsZTTPLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_InsertarFatom0R20.
        /// </summary>
        internal static string sp_InsertarFatom0R20 {
            get {
                return ResourceManager.GetString("sp_InsertarFatom0R20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_InsertaZmaster.
        /// </summary>
        internal static string sp_InsertaZmaster {
            get {
                return ResourceManager.GetString("sp_InsertaZmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_InsLogs.
        /// </summary>
        internal static string sp_InsLogs {
            get {
                return ResourceManager.GetString("sp_InsLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_InsTabTemZMaster.
        /// </summary>
        internal static string sp_InsTabTemZMaster {
            get {
                return ResourceManager.GetString("sp_InsTabTemZMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_InsTarimaTemporal.
        /// </summary>
        internal static string sp_InsTarimaTemporal {
            get {
                return ResourceManager.GetString("sp_InsTarimaTemporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_InsUsuarios.
        /// </summary>
        internal static string sp_InsUsuarios {
            get {
                return ResourceManager.GetString("sp_InsUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_InsZ_CAT.
        /// </summary>
        internal static string sp_InsZ_CAT {
            get {
                return ResourceManager.GetString("sp_InsZ_CAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_InsZ_CTC.
        /// </summary>
        internal static string sp_InsZ_CTC {
            get {
                return ResourceManager.GetString("sp_InsZ_CTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_InsZMaster.
        /// </summary>
        internal static string sp_InsZMaster {
            get {
                return ResourceManager.GetString("sp_InsZMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_InsZPPG01_FATOM.
        /// </summary>
        internal static string sp_InsZPPG01_FATOM {
            get {
                return ResourceManager.GetString("sp_InsZPPG01_FATOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ModLips.
        /// </summary>
        internal static string sp_ModLips {
            get {
                return ResourceManager.GetString("sp_ModLips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ModUsuarios.
        /// </summary>
        internal static string sp_ModUsuarios {
            get {
                return ResourceManager.GetString("sp_ModUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sp_ModZMaster.
        /// </summary>
        internal static string sp_ModZMaster {
            get {
                return ResourceManager.GetString("sp_ModZMaster", resourceCulture);
            }
        }
    }
}
