//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contingencia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Variables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Variables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contingencia.Variables", typeof(Variables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se actualizó correctamente..
        /// </summary>
        internal static string ActualizacionCorrecta {
            get {
                return ResourceManager.GetString("ActualizacionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string Administrador {
            get {
                return ResourceManager.GetString("Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta.
        /// </summary>
        internal static string Alta {
            get {
                return ResourceManager.GetString("Alta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.ini.
        /// </summary>
        internal static string ArchivoConfiguracion {
            get {
                return ResourceManager.GetString("ArchivoConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string Asterisco {
            get {
                return ResourceManager.GetString("Asterisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baja.
        /// </summary>
        internal static string Baja {
            get {
                return ResourceManager.GetString("Baja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Blanco {
            get {
                return ResourceManager.GetString("Blanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Cero {
            get {
                return ResourceManager.GetString("Cero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string Coma {
            get {
                return ResourceManager.GetString("Coma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        internal static string CorcheteAbre {
            get {
                return ResourceManager.GetString("CorcheteAbre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        internal static string CorcheteCierra {
            get {
                return ResourceManager.GetString("CorcheteCierra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es-Mx.
        /// </summary>
        internal static string Cultura {
            get {
                return ResourceManager.GetString("Cultura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string CulturaUS {
            get {
                return ResourceManager.GetString("CulturaUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string DesNivelA {
            get {
                return ResourceManager.GetString("DesNivelA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operador.
        /// </summary>
        internal static string DesNivelO {
            get {
                return ResourceManager.GetString("DesNivelO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        internal static string DesNivelS {
            get {
                return ResourceManager.GetString("DesNivelS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string DiagonalDerecha {
            get {
                return ResourceManager.GetString("DiagonalDerecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        internal static string DiagonalIzquierda {
            get {
                return ResourceManager.GetString("DiagonalIzquierda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string DosPuntos {
            get {
                return ResourceManager.GetString("DosPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se eliminó correctamente..
        /// </summary>
        internal static string EliminarCorrecto {
            get {
                return ResourceManager.GetString("EliminarCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Espacio {
            get {
                return ResourceManager.GetString("Espacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                                                                                                                                 .
        /// </summary>
        internal static string EspaciosDoscien {
            get {
                return ResourceManager.GetString("EspaciosDoscien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEL.
        /// </summary>
        internal static string ListaEliminar {
            get {
                return ResourceManager.GetString("ListaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INS.
        /// </summary>
        internal static string ListaInsertar {
            get {
                return ResourceManager.GetString("ListaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOD.
        /// </summary>
        internal static string ListaModificar {
            get {
                return ResourceManager.GetString("ListaModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUEVA.
        /// </summary>
        internal static string ListaNueva {
            get {
                return ResourceManager.GetString("ListaNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string llaveFin {
            get {
                return ResourceManager.GetString("llaveFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        internal static string llaveInicio {
            get {
                return ResourceManager.GetString("llaveInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN.
        /// </summary>
        internal static string NivelAdmin {
            get {
                return ResourceManager.GetString("NivelAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPER.
        /// </summary>
        internal static string NivelOper {
            get {
                return ResourceManager.GetString("NivelOper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPER.
        /// </summary>
        internal static string NivelSuper {
            get {
                return ResourceManager.GetString("NivelSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contingencia.exe.
        /// </summary>
        internal static string NombreAssambly {
            get {
                return ResourceManager.GetString("NombreAssambly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contingencia.
        /// </summary>
        internal static string NombreSistema {
            get {
                return ResourceManager.GetString("NombreSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Nulo {
            get {
                return ResourceManager.GetString("Nulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número no válido..
        /// </summary>
        internal static string NumeroInvalido {
            get {
                return ResourceManager.GetString("NumeroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        internal static string OperacionDELETE {
            get {
                return ResourceManager.GetString("OperacionDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT.
        /// </summary>
        internal static string OperacionINSERT {
            get {
                return ResourceManager.GetString("OperacionINSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        internal static string OperacionUPDATE {
            get {
                return ResourceManager.GetString("OperacionUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string Operador {
            get {
                return ResourceManager.GetString("Operador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string Paloma {
            get {
                return ResourceManager.GetString("Paloma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spw.
        /// </summary>
        internal static string PasswordBd {
            get {
                return ResourceManager.GetString("PasswordBd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string Pipe {
            get {
                return ResourceManager.GetString("Pipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar registro?.
        /// </summary>
        internal static string PreguntaEliminar {
            get {
                return ResourceManager.GetString("PreguntaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se guardó correctamente..
        /// </summary>
        internal static string RegistroCorrecto {
            get {
                return ResourceManager.GetString("RegistroCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sbd.
        /// </summary>
        internal static string Servidor {
            get {
                return ResourceManager.GetString("Servidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        internal static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sop.
        /// </summary>
        internal static string SistemaOperativo {
            get {
                return ResourceManager.GetString("SistemaOperativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string Tache {
            get {
                return ResourceManager.GetString("Tache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string TipoDatoDecimal {
            get {
                return ResourceManager.GetString("TipoDatoDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        internal static string TipoDatoDouble {
            get {
                return ResourceManager.GetString("TipoDatoDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string TipoDatoFecha {
            get {
                return ResourceManager.GetString("TipoDatoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int.
        /// </summary>
        internal static string TipoDatoInt {
            get {
                return ResourceManager.GetString("TipoDatoInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string TipoDatoString {
            get {
                return ResourceManager.GetString("TipoDatoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModificarCuenta.
        /// </summary>
        internal static string TipoProcesoModificarCuenta {
            get {
                return ResourceManager.GetString("TipoProcesoModificarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModificarEstado.
        /// </summary>
        internal static string TipoProcesoModificarEstado {
            get {
                return ResourceManager.GetString("TipoProcesoModificarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModificarGestor.
        /// </summary>
        internal static string TipoProcesoModificarGestor {
            get {
                return ResourceManager.GetString("TipoProcesoModificarGestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string UsuarioActivo {
            get {
                return ResourceManager.GetString("UsuarioActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string UsuarioBaja {
            get {
                return ResourceManager.GetString("UsuarioBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sus.
        /// </summary>
        internal static string UsuarioBd {
            get {
                return ResourceManager.GetString("UsuarioBd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string UsuarioInactivo {
            get {
                return ResourceManager.GetString("UsuarioInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo.
        /// </summary>
        internal static string VarPeriodo {
            get {
                return ResourceManager.GetString("VarPeriodo", resourceCulture);
            }
        }
    }
}
